#pragma once

#define PCI_ID_REG 0x00
#define PCI_VENDOR(id) ((id) & 0xFFFF)
#define PCI_PRODUCT(id) (((id) >> 16) & 0xFFFF)

#define PCI_CLASS_REG 0x08
#define PCI_CLASS_SHIFT 24
#define PCI_CLASS_MASK 0xFF
#define PCI_SUBCLASS_SHIFT 16
#define PCI_SUBCLASS_MASK 0xFF
#define PCI_INTERFACE_SHIFT 8
#define PCI_INTERFACE_MASK 0xFF
#define PCI_REVISION_SHIFT 0
#define PCI_REVISION_MASK 0xFF

#define PCI_CLASS(cr) (((cr) >> PCI_CLASS_SHIFT) & PCI_CLASS_MASK)
#define PCI_SUBCLASS(cr) (((cr) >> PCI_SUBCLASS_SHIFT) & PCI_SUBCLASS_MASK)
#define PCI_INTERFACE(cr) (((cr) >> PCI_INTERFACE_SHIFT) & PCI_INTERFACE_MASK)
#define PCI_REVISION(cr) (((cr) >> PCI_REVISION_SHIFT) & PCI_REVISION_MASK)

#define PCI_CLASS_DISPLAY 0x03
#define PCI_SUBCLASS_DISPLAY_VGA 0x00

#define PCI_CLASS_BRIDGE 0x06
#define PCI_SUBCLASS_BRIDGE_ISA 0x01

#define PCI_COMMAND_STATUS_REG 0x04
#define PCI_SUBSYS_ID_REG 0x2C
#define PCI_BHLC_REG 0x0C
#define PCI_HDRTYPE_TYPE(bhlc) (((bhlc) >> 16) & 0x7f)

#define PCI_PCIE_XCAP 0x02
#define PCI_PCIE_XCAP_VER(x) (((x) >> 4) & 0xf)
#define PCI_PCIE_LCAP 0x0c
#define PCI_PCIE_LCAP2 0x2c
#define PCI_PCIE_LCSR 0x10
#define PCI_PCIE_LCSR_ASPM_L0S 0x00000001
#define PCI_PCIE_LCSR_ASPM_L1 0x00000002
#define PCI_PCIE_ECAP 0x100
#define PCI_PCIE_ECAP_ID(x) ((x) & 0xffff)
#define PCI_PCIE_ECAP_NEXT(x) (((x) >> 20) & 0xffc)
#define PCI_COMMAND_IO_ENABLE 0x00000001
#define PCI_COMMAND_MEM_ENABLE 0x00000002
#define PCI_COMMAND_MASTER_ENABLE 0x00000004

#define PCI_MAPREG_START 0x10
#define PCI_MAPREG_END 0x28
#define PCI_MAPREG_TYPE_MASK 0x00000001
#define PCI_MAPREG_TYPE_MEM 0x00000000
#define PCI_MAPREG_TYPE_IO 0x00000001
#define PCI_MAPREG_MEM_TYPE_MASK 0x00000006
#define PCI_MAPREG_MEM_TYPE_32BIT 0x00000000
#define PCI_MAPREG_MEM_TYPE_64BIT 0x00000004
#define PCI_MAPREG_MEM_ADDR_MASK 0xFFFFFFF0
#define PCI_MAPREG_MEM_PREFETCHABLE_MASK 0x00000008

#define PCI_BHLC_REG 0x0c
#define PCI_HDRTYPE_SHIFT 16
#define PCI_HDRTYPE_MASK 0x7F
#define PCI_HDRTYPE(bhlcr) (((bhlcr) >> PCI_HDRTYPE_SHIFT) & PCI_HDRTYPE_MASK)

#define PCI_CAPLISTPTR_REG 0x34

#define PCI_CAP_PCIEXPRESS 0x10

#define PCI_PCIE_DCSR 0x08
#define PCI_PCIE_DCSR_MPS 0x00E0
#define PCI_PCIE_DCSR_MPS_SHIFT 5
#define PCI_PCIE_DCSR_MRRS 0x7000
#define PCI_PCIE_DCSR_MRRS_SHIFT 12
