use std::env;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let csrc_dir = manifest_dir.join("csrc");
    let include_dir = manifest_dir.join("include");
    let compat_include_dir = manifest_dir.join("../../../../compat/libc/include");
    let vdrm_dir = manifest_dir.join("../../../../../vendors/openbsd-drm");

    println!("cargo:rerun-if-changed={}", csrc_dir.display());
    println!("cargo:rerun-if-changed={}", include_dir.display());

    let mut objects = Vec::new();

    let mut sources: Vec<PathBuf> = Vec::new();
    for entry in std::fs::read_dir(&csrc_dir).unwrap() {
        let path = entry.unwrap().path();
        if path.extension().and_then(|e| e.to_str()) == Some("c") {
            sources.push(path);
        }
    }
    sources.push(vdrm_dir.join("i915/display/intel_atomic.c"));
    sources.push(vdrm_dir.join("i915/display/intel_crtc.c"));
    sources.push(vdrm_dir.join("i915/display/intel_connector.c"));
    sources.push(vdrm_dir.join("i915/display/intel_encoder.c"));
    sources.push(vdrm_dir.join("i915/display/intel_global_state.c"));
    sources.push(vdrm_dir.join("i915/display/intel_bo.c"));
    sources.push(vdrm_dir.join("i915/display/intel_fb.c"));
    sources.push(vdrm_dir.join("i915/display/intel_plane.c"));
    sources.push(vdrm_dir.join("i915/display/intel_display_power_map.c"));
    sources.push(vdrm_dir.join("i915/display/intel_dpll.c"));
    sources.push(vdrm_dir.join("i915/display/intel_dpll_mgr.c"));
    sources.push(vdrm_dir.join("i915/display/intel_display_power.c"));
    sources.push(vdrm_dir.join("i915/display/intel_display_power_well.c"));
    sources.push(vdrm_dir.join("i915/display/intel_ddi.c"));
    sources.push(vdrm_dir.join("i915/display/intel_cdclk.c"));
    sources.push(vdrm_dir.join("i915/display/intel_ddi_buf_trans.c"));
    sources.push(vdrm_dir.join("i915/display/intel_dp_link_training.c"));
    sources.push(vdrm_dir.join("i915/display/intel_hdmi.c"));
    sources.push(vdrm_dir.join("i915/display/intel_dp.c"));
    sources.push(vdrm_dir.join("i915/display/intel_dpt.c"));
    sources.push(vdrm_dir.join("i915/display/intel_dsb.c"));
    sources.push(vdrm_dir.join("i915/display/intel_wm.c"));
    sources.push(vdrm_dir.join("i915/display/skl_watermark.c"));
    sources.push(vdrm_dir.join("i915/display/intel_cx0_phy.c"));
    sources.push(vdrm_dir.join("i915/display/i9xx_wm.c"));
    sources.push(vdrm_dir.join("i915/display/intel_vblank.c"));
    sources.push(vdrm_dir.join("i915/display/intel_vrr.c"));
    sources.push(vdrm_dir.join("i915/display/intel_psr.c"));
    sources.push(vdrm_dir.join("i915/display/intel_fbc.c"));
    sources.push(vdrm_dir.join("i915/display/intel_color.c"));
    sources.push(vdrm_dir.join("i915/display/intel_cursor.c"));
    sources.push(vdrm_dir.join("i915/display/intel_sprite.c"));
    sources.push(vdrm_dir.join("i915/display/skl_universal_plane.c"));
    sources.push(vdrm_dir.join("i915/display/i9xx_plane.c"));
    sources.push(vdrm_dir.join("i915/display/intel_hotplug.c"));
    sources.push(vdrm_dir.join("i915/display/intel_backlight.c"));
    sources.push(vdrm_dir.join("i915/display/intel_pch.c"));
    sources.push(vdrm_dir.join("i915/display/intel_pch_display.c"));
    sources.push(vdrm_dir.join("i915/display/intel_fdi.c"));
    sources.push(vdrm_dir.join("i915/display/intel_modeset_setup.c"));
    sources.push(vdrm_dir.join("i915/display/intel_pfit.c"));
    sources.push(vdrm_dir.join("i915/display/intel_display.c"));
    sources.push(vdrm_dir.join("i915/display/intel_display_driver.c"));
    sources.push(vdrm_dir.join("i915/i915_pci.c"));
    sources.push(vdrm_dir.join("i915/intel_device_info.c"));
    sources.push(vdrm_dir.join("i915/i915_driver.c"));
    sources.push(vdrm_dir.join("i915/display/intel_display_irq.c"));
    sources.push(vdrm_dir.join("i915/display/intel_display_rpm.c"));
    sources.push(vdrm_dir.join("i915/display/intel_sbi.c"));
    sources.push(vdrm_dir.join("i915/intel_step.c"));
    sources.push(vdrm_dir.join("i915/vlv_iosf_sb.c"));
    sources.push(vdrm_dir.join("i915/display/intel_dmc_wl.c"));
    sources.push(vdrm_dir.join("i915/intel_uncore.c"));
    sources.push(vdrm_dir.join("display/drm_dp_helper.c"));
    sources.push(vdrm_dir.join("drm_crtc.c"));
    sources.push(vdrm_dir.join("drm_print.c"));
    sources.push(vdrm_dir.join("drm_atomic_state_helper.c"));
    sources.push(vdrm_dir.join("drm_client_event.c"));
    sources.push(vdrm_dir.join("i915/display/intel_display_conversion.c"));
    sources.push(vdrm_dir.join("i915/display/intel_hotplug_irq.c"));
    sources.push(vdrm_dir.join("i915/gem/i915_gem_domain.c"));
    sources.push(vdrm_dir.join("i915/gem/i915_gem_object.c"));
    sources.push(vdrm_dir.join("i915/display/intel_alpm.c"));
    sources.push(vdrm_dir.join("i915/display/intel_bios.c"));
    sources.push(vdrm_dir.join("i915/display/intel_hdcp.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_gt.c"));
    sources.push(vdrm_dir.join("i915/intel_region_ttm.c"));
    sources.push(vdrm_dir.join("i915/intel_runtime_pm.c"));
    sources.push(vdrm_dir.join("i915/i915_vgpu.c"));
    sources.push(vdrm_dir.join("i915/vlv_suspend.c"));
    sources.push(vdrm_dir.join("drm_fb_helper.c"));
    sources.push(vdrm_dir.join("drm_probe_helper.c"));
    sources.push(vdrm_dir.join("drm_managed.c"));
    sources.push(vdrm_dir.join("i915/i915_memcpy.c"));
    sources.push(vdrm_dir.join("drm_vblank.c"));
    sources.push(vdrm_dir.join("drm_modeset_lock.c"));
    sources.push(vdrm_dir.join("i915/gem/i915_gem_pm.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_ggtt.c"));
    sources.push(vdrm_dir.join("i915/i915_perf.c"));
    sources.push(vdrm_dir.join("i915/i915_utils.c"));
    sources.push(vdrm_dir.join("i915/display/intel_audio.c"));
    sources.push(vdrm_dir.join("i915/display/intel_dkl_phy.c"));
    sources.push(vdrm_dir.join("i915/soc/intel_dram.c"));
    sources.push(vdrm_dir.join("i915/i915_irq.c"));
    sources.push(vdrm_dir.join("i915/intel_memory_region.c"));
    sources.push(vdrm_dir.join("i915/intel_pcode.c"));
    sources.push(vdrm_dir.join("i915/display/intel_tc.c"));
    sources.push(vdrm_dir.join("drm_plane.c"));
    sources.push(vdrm_dir.join("drm_blend.c"));
    sources.push(vdrm_dir.join("drm_connector.c"));
    sources.push(vdrm_dir.join("drm_fourcc.c"));
    sources.push(vdrm_dir.join("i915/i915_gem.c"));
    sources.push(vdrm_dir.join("i915/intel_clock_gating.c"));
    sources.push(vdrm_dir.join("i915/display/intel_display_device.c"));
    sources.push(vdrm_dir.join("i915/display/intel_vdsc.c"));
    sources.push(vdrm_dir.join("i915/soc/intel_gmch.c"));
    sources.push(vdrm_dir.join("i915/display/intel_lvds.c"));
    sources.push(vdrm_dir.join("i915/display/intel_vga.c"));
    sources.push(vdrm_dir.join("i915/display/intel_dpio_phy.c"));
    sources.push(vdrm_dir.join("drm_mode_config.c"));
    sources.push(vdrm_dir.join("drm_color_mgmt.c"));
    sources.push(vdrm_dir.join("i915/display/intel_bw.c"));
    sources.push(vdrm_dir.join("i915/display/intel_dmc.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_reset.c"));
    sources.push(vdrm_dir.join("i915/display/intel_fifo_underrun.c"));
    sources.push(vdrm_dir.join("i915/display/intel_quirks.c"));
    sources.push(vdrm_dir.join("i915/display/intel_modeset_lock.c"));
    sources.push(vdrm_dir.join("i915/display/intel_pmdemand.c"));
    sources.push(vdrm_dir.join("i915/display/intel_snps_phy.c"));
    sources.push(vdrm_dir.join("i915/display/vlv_dsi_pll.c"));
    sources.push(vdrm_dir.join("drm_drv.c"));
    sources.push(vdrm_dir.join("drm_property.c"));
    sources.push(vdrm_dir.join("drm_modes.c"));
    sources.push(vdrm_dir.join("i915/display/hsw_ips.c"));
    sources.push(vdrm_dir.join("i915/i915_params.c"));
    sources.push(vdrm_dir.join("i915/i915_sysfs.c"));
    sources.push(vdrm_dir.join("i915/i915_switcheroo.c"));
    sources.push(vdrm_dir.join("i915/display/intel_display_wa.c"));
    sources.push(vdrm_dir.join("i915/display/intel_drrs.c"));
    sources.push(vdrm_dir.join("i915/display/intel_gmbus.c"));
    sources.push(vdrm_dir.join("i915/display/intel_plane_initial.c"));
    sources.push(vdrm_dir.join("i915/display/intel_pps.c"));
    sources.push(vdrm_dir.join("display/drm_hdmi_state_helper.c"));
    sources.push(vdrm_dir.join("display/drm_dsc_helper.c"));
    sources.push(vdrm_dir.join("drm_encoder.c"));
    sources.push(vdrm_dir.join("drm_mode_object.c"));
    sources.push(vdrm_dir.join("drm_vblank_work.c"));
    sources.push(vdrm_dir.join("i915/display/icl_dsi.c"));
    sources.push(vdrm_dir.join("i915/display/intel_combo_phy.c"));
    sources.push(vdrm_dir.join("i915/display/intel_dp_mst.c"));
    sources.push(vdrm_dir.join("i915/display/intel_dp_test.c"));
    sources.push(vdrm_dir.join("i915/display/intel_flipq.c"));
    sources.push(vdrm_dir.join("i915/display/intel_hti.c"));
    sources.push(vdrm_dir.join("i915/display/skl_scaler.c"));
    sources.push(vdrm_dir.join("i915/display/vlv_sideband.c"));
    sources.push(vdrm_dir.join("i915/display/vlv_dsi.c"));
    sources.push(vdrm_dir.join("drm_linux.c"));
    sources.push(vdrm_dir.join("drm_atomic.c"));
    sources.push(vdrm_dir.join("display/drm_dp_mst_topology.c"));
    sources.push(vdrm_dir.join("i915/gem/i915_gem_mman.c"));
    sources.push(vdrm_dir.join("drm_atomic_uapi.c"));
    sources.push(vdrm_dir.join("display/drm_hdcp_helper.c"));
    sources.push(vdrm_dir.join("i915/gem/i915_gem_create.c"));
    sources.push(vdrm_dir.join("i915/gem/i915_gem_stolen.c"));
    sources.push(vdrm_dir.join("drm_gem.c"));
    sources.push(vdrm_dir.join("i915/i915_request.c"));
    sources.push(vdrm_dir.join("i915/gem/i915_gem_tiling.c"));
    sources.push(vdrm_dir.join("i915/gem/i915_gem_context.c"));
    sources.push(vdrm_dir.join("i915/gem/i915_gem_wait.c"));
    sources.push(vdrm_dir.join("i915/gem/i915_gem_pages.c"));
    sources.push(vdrm_dir.join("hdmi.c"));
    sources.push(vdrm_dir.join("drm_bridge.c"));
    sources.push(vdrm_dir.join("drm_gem_atomic_helper.c"));
    sources.push(vdrm_dir.join("drm_crtc_helper.c"));
    sources.push(vdrm_dir.join("linux_sort_r.c"));
    sources.push(vdrm_dir.join("drm_displayid.c"));
    sources.push(vdrm_dir.join("linux_list_sort.c"));
    sources.push(vdrm_dir.join("drm_cache.c"));
    sources.push(vdrm_dir.join("i915/i915_vma.c"));
    sources.push(vdrm_dir.join("i915/i915_config.c"));
    sources.push(vdrm_dir.join("i915/display/intel_fb_bo.c"));
    sources.push(vdrm_dir.join("i915/display/intel_fb_pin.c"));
    sources.push(vdrm_dir.join("i915/display/intel_frontbuffer.c"));
    sources.push(vdrm_dir.join("i915/display/intel_tv.c"));
    sources.push(vdrm_dir.join("i915/display/intel_dsi.c"));
    sources.push(vdrm_dir.join("i915/display/intel_link_bw.c"));
    sources.push(vdrm_dir.join("i915/gem/i915_gem_userptr.c"));
    sources.push(vdrm_dir.join("i915/gem/i915_gem_lmem.c"));
    sources.push(vdrm_dir.join("i915/gem/i915_gem_execbuffer.c"));
    sources.push(vdrm_dir.join("i915/gem/i915_gem_busy.c"));
    sources.push(vdrm_dir.join("i915/gem/i915_gem_throttle.c"));
    sources.push(vdrm_dir.join("i915/gem/i915_gem_region.c"));
    sources.push(vdrm_dir.join("i915/gem/i915_gem_shmem.c"));
    sources.push(vdrm_dir.join("i915/gem/i915_gem_internal.c"));
    sources.push(vdrm_dir.join("i915/gem/i915_gem_ttm.c"));
    sources.push(vdrm_dir.join("i915/gt/shmem_utils.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_engine_user.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_context.c"));
    sources.push(vdrm_dir.join("drm_damage_helper.c"));
    sources.push(vdrm_dir.join("drm_atomic_helper.c"));
    sources.push(vdrm_dir.join("drm_edid.c"));
    sources.push(vdrm_dir.join("drm_panel_orientation_quirks.c"));
    sources.push(vdrm_dir.join("drm_rect.c"));
    sources.push(vdrm_dir.join("i915/i915_module.c"));
    sources.push(vdrm_dir.join("i915/display/intel_fbdev.c"));
    sources.push(vdrm_dir.join("i915/intel_stolen.c"));
    sources.push(vdrm_dir.join("i915/display/intel_overlay.c"));
    sources.push(vdrm_dir.join("i915/display/intel_panel.c"));
    sources.push(vdrm_dir.join("clients/drm_client_setup.c"));
    sources.push(vdrm_dir.join("display/drm_dp_dual_mode_helper.c"));
    sources.push(vdrm_dir.join("display/drm_hdmi_helper.c"));
    sources.push(vdrm_dir.join("display/drm_scdc_helper.c"));
    sources.push(vdrm_dir.join("dma-resv.c"));
    sources.push(vdrm_dir.join("drm_auth.c"));
    sources.push(vdrm_dir.join("drm_client.c"));
    sources.push(vdrm_dir.join("drm_client_modeset.c"));
    sources.push(vdrm_dir.join("drm_file.c"));
    sources.push(vdrm_dir.join("drm_framebuffer.c"));
    sources.push(vdrm_dir.join("drm_ioctl.c"));
    sources.push(vdrm_dir.join("drm_mipi_dsi.c"));
    sources.push(vdrm_dir.join("drm_mm.c"));
    sources.push(vdrm_dir.join("drm_modeset_helper.c"));
    sources.push(vdrm_dir.join("drm_panel.c"));
    sources.push(vdrm_dir.join("drm_prime.c"));
    sources.push(vdrm_dir.join("drm_syncobj.c"));
    sources.push(vdrm_dir.join("drm_vma_manager.c"));
    sources.push(vdrm_dir.join("i915/display/g4x_dp.c"));
    sources.push(vdrm_dir.join("i915/display/g4x_hdmi.c"));
    sources.push(vdrm_dir.join("i915/display/intel_cmtg.c"));
    sources.push(vdrm_dir.join("i915/display/intel_crt.c"));
    sources.push(vdrm_dir.join("i915/display/intel_crtc_state_dump.c"));
    sources.push(vdrm_dir.join("i915/display/intel_display_params.c"));
    sources.push(vdrm_dir.join("i915/display/intel_display_reset.c"));
    sources.push(vdrm_dir.join("i915/display/intel_display_rps.c"));
    sources.push(vdrm_dir.join("i915/display/intel_dp_aux.c"));
    sources.push(vdrm_dir.join("i915/display/intel_dp_aux_backlight.c"));
    sources.push(vdrm_dir.join("i915/display/intel_dp_hdcp.c"));
    sources.push(vdrm_dir.join("i915/display/intel_dpt_common.c"));
    sources.push(vdrm_dir.join("i915/display/intel_dsb_buffer.c"));
    sources.push(vdrm_dir.join("i915/display/intel_dsi_dcs_backlight.c"));
    sources.push(vdrm_dir.join("i915/display/intel_dsi_vbt.c"));
    sources.push(vdrm_dir.join("i915/display/intel_dvo.c"));
    sources.push(vdrm_dir.join("i915/display/intel_fbdev_fb.c"));
    sources.push(vdrm_dir.join("i915/display/intel_hdcp_gsc_message.c"));
    sources.push(vdrm_dir.join("i915/display/intel_load_detect.c"));
    sources.push(vdrm_dir.join("i915/display/intel_lpe_audio.c"));
    sources.push(vdrm_dir.join("i915/display/intel_lspcon.c"));
    sources.push(vdrm_dir.join("i915/display/intel_modeset_verify.c"));
    sources.push(vdrm_dir.join("i915/display/intel_panic.c"));
    sources.push(vdrm_dir.join("i915/display/intel_pch_refclk.c"));
    sources.push(vdrm_dir.join("i915/display/intel_sdvo.c"));
    sources.push(vdrm_dir.join("i915/display/intel_snps_hdmi_pll.c"));
    sources.push(vdrm_dir.join("i915/display/intel_sprite_uapi.c"));
    sources.push(vdrm_dir.join("i915/gem/i915_gem_clflush.c"));
    sources.push(vdrm_dir.join("i915/gem/i915_gem_dmabuf.c"));
    sources.push(vdrm_dir.join("i915/gem/i915_gem_phys.c"));
    sources.push(vdrm_dir.join("i915/gem/i915_gem_shrinker.c"));
    sources.push(vdrm_dir.join("i915/gem/i915_gem_ttm_move.c"));
    sources.push(vdrm_dir.join("i915/gem/i915_gem_ttm_pm.c"));
    sources.push(vdrm_dir.join("i915/gem/i915_gemfs.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_breadcrumbs.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_context_sseu.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_engine_cs.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_engine_heartbeat.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_ggtt_fencing.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_ggtt_gmch.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_gsc.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_gt_buffer_pool.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_gt_clock_utils.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_gt_debugfs.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_gt_irq.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_gt_mcr.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_gt_pm.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_gt_requests.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_gt_sysfs.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_gtt.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_migrate.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_mocs.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_ppgtt.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_rc6.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_region_lmem.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_renderstate.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_ring.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_rps.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_sseu.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_timeline.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_tlb.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_wopcm.c"));
    sources.push(vdrm_dir.join("i915/gt/intel_workarounds.c"));
    sources.push(vdrm_dir.join("i915/gt/uc/intel_gsc_fw.c"));
    sources.push(vdrm_dir.join("i915/gt/uc/intel_guc_hwconfig.c"));
    sources.push(vdrm_dir.join("i915/gt/uc/intel_guc_submission.c"));
    sources.push(vdrm_dir.join("i915/gt/uc/intel_huc.c"));
    sources.push(vdrm_dir.join("i915/gt/uc/intel_uc.c"));
    sources.push(vdrm_dir.join("i915/i915_active.c"));
    sources.push(vdrm_dir.join("i915/i915_cmd_parser.c"));
    sources.push(vdrm_dir.join("i915/i915_drm_client.c"));
    sources.push(vdrm_dir.join("i915/i915_gem_evict.c"));
    sources.push(vdrm_dir.join("i915/i915_gem_gtt.c"));
    sources.push(vdrm_dir.join("i915/i915_gem_ww.c"));
    sources.push(vdrm_dir.join("i915/i915_getparam.c"));
    sources.push(vdrm_dir.join("i915/i915_gpu_error.c"));
    sources.push(vdrm_dir.join("i915/i915_ioctl.c"));
    sources.push(vdrm_dir.join("i915/i915_query.c"));
    sources.push(vdrm_dir.join("i915/i915_scatterlist.c"));
    sources.push(vdrm_dir.join("i915/i915_scheduler.c"));
    sources.push(vdrm_dir.join("i915/i915_sw_fence.c"));
    sources.push(vdrm_dir.join("i915/i915_sw_fence_work.c"));
    sources.push(vdrm_dir.join("i915/i915_syncmap.c"));
    sources.push(vdrm_dir.join("i915/i915_ttm_buddy_manager.c"));
    sources.push(vdrm_dir.join("i915/i915_user_extensions.c"));
    sources.push(vdrm_dir.join("i915/i915_vma_resource.c"));
    sources.push(vdrm_dir.join("i915/intel_cpu_info.c"));
    sources.push(vdrm_dir.join("i915/intel_wakeref.c"));
    sources.push(vdrm_dir.join("i915/soc/intel_rom.c"));
    sources.push(vdrm_dir.join("linux_radix.c"));

    for path in sources {
        let obj_name = path.file_stem().unwrap().to_str().unwrap().to_string();
        let obj = out_dir.join(format!("{obj_name}.o"));

        let status = Command::new("clang")
            .arg("--target=x86_64-unknown-none-elf")
            .arg("-ffreestanding")
            .arg("-nostdlib")
            .arg("-nostdinc")
            .arg("-isystem")
            .arg("/usr/lib/clang/22/include")
            .arg("-isystem")
            .arg(&include_dir)
            .arg("-isystem")
            .arg(&compat_include_dir)
            .arg("-I")
            .arg(vdrm_dir.join("include"))
            .arg("-I")
            .arg(vdrm_dir.join("include/uapi"))
            .arg("-I")
            .arg(vdrm_dir.join("i915/display"))
            .arg("-I")
            .arg(vdrm_dir.join("i915"))
            .arg("-I")
            .arg(&vdrm_dir)
            .arg("-DI915")
            .arg("-D__OpenBSD__")
            .arg("-D_KERNEL")
            .arg("-mno-red-zone")
            .arg("-mno-mmx")
            .arg("-mno-sse")
            .arg("-mno-sse2")
            .arg("-std=gnu11")
            .arg("-fdata-sections")
            .arg("-ffunction-sections")
            .arg("-O2")
            .arg("-c")
            .arg(&path)
            .arg("-o")
            .arg(&obj)
            .status()
            .expect("failed to spawn clang");

        assert!(status.success(), "clang failed on {}", path.display());
        objects.push(obj);
    }

    let lib_path = out_dir.join("libi915shim.a");
    let status = Command::new("ar")
        .arg("rcs")
        .arg(&lib_path)
        .args(&objects)
        .status()
        .expect("failed to spawn ar");
    assert!(status.success(), "ar failed");

    println!("cargo:rustc-link-search=native={}", out_dir.display());
    println!("cargo:rustc-link-lib=static=i915shim");
}
